<html>
<head>
    <meta charset="UTF-8">
    <title>InfoShareAcademy</title>
</head>
<body>
<p><b>${name}</b></p>
<p><b>${team}</b></p>
<p><b>${time}</b></p>

<form action="/infoShareAcademy" method="post">
    param1:<br>
    <input type="text" name="param1"><br><br>
    param2:<br>
    <input type="text" name="param2"><br><br>
    param3:<br>
    <input type="text" name="param3"><br><br>
    param3:<br>
    <input type="text" name="param3"><br><br>
    <input type="submit" value="Submit">
</form>
</body>
</html>